import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const tips={info:'Здесь собраны папки, в которых вы работали с Kilo. Чтобы вернуться к работе, выберите папку и откройте её.',refresh:'Обновить список папок и диалогов из Kilo',history:'До трёх последних диалогов. Открыть и продолжить их можно в Kilo Code',missing:'Папка не найдена по сохранённому пути. Возможно, её переместили или удалили. Открытие недоступно'};
const actions=[['Открыть в этом окне','Выбранная папка откроется вместо текущей в этом окне VS Code'],['Открыть в отдельном окне','Текущая папка останется открытой'],['Показать файлы папки','Откроется Проводник Windows']];
export function renderActions(current,missing){
 if(missing)return '';
 const available=current?actions.slice(2):actions;
 return `<div class="actions">${available.map(([label,tip])=>`<button data-tip="${tip}">${label}</button>`).join('')}</div>`;
}
const folders=[['Сайт мастерской','СМ','mint',8,true,false],['Семейный бюджет','СБ','peach',0,false,false],['Путешествие по северу','ПС','lavender',1,false,false],['Каталог работ и вдохновения для новой коллекции','КР','blue',3,false,false],['Старый эксперимент','СЭ','gray',40,false,true]];
function panel(kind,theme){return `<section class="panel ${kind} demo-${theme}" aria-label="Kilo Hub"><header><strong>Kilo Hub</strong><button class="refresh" data-tip="${tips.refresh}" aria-label="${tips.refresh}">↻</button></header><div class="intro"><h2>Мои папки с Kilo</h2><button class="info" aria-label="О списке папок" data-tip="${tips.info}">ⓘ</button></div><p class="demo-status" role="status"></p><div class="folders">${folders.map(([name,mono,tone,days,current,missing],i)=>{const id=`${theme}-${i}`;const open=i===1;return `<article class="folder ${tone} ${current?'current':''} ${missing?'missing':''} ${open?'expanded':''}" data-id="${i}" data-name="${esc(name)}" data-days="${days}" data-activity="${new Date(Date.parse('2026-09-20T00:00:00+03:00')-days*86400000).toISOString()}"><div class="folder-head" role="button" tabindex="0" aria-expanded="${open}" aria-controls="${id}"><span class="mono" aria-hidden="true">${mono}</span><span class="identity">${current?'<span class="current-label">Вы сейчас здесь</span>':''}<span class="name" data-tip="D:\\Примеры\\${esc(name)}">${esc(name)}</span><span class="activity" tabindex="0"></span>${missing?`<span class="missing-label" tabindex="0" data-tip="${tips.missing}">Папка не найдена</span>`:''}</span><span class="chevron" aria-hidden="true">⌄</span></div><div class="detail-wrap ${open?'open':''}" id="${id}" ${open?'':'inert aria-hidden="true"'}><div class="detail">${renderActions(current,missing)}<div class="history"><h3 tabindex="0" data-tip="${tips.history}">Последние диалоги</h3>${(missing?['Первые наброски']:['План расходов на осень','Как наглядно сравнить расходы за несколько месяцев','Без названия']).map(t=>`<p class="dialogue" tabindex="0" data-tip="${esc(t)}">${esc(t)}</p>`).join('')}</div></div></div></article>`;}).join('')}</div><div class="tooltip" role="tooltip" hidden></div></section>`;}
const labels={original:'Оригинальная',dark:'Тёмная',light:'Светлая',contrast:'Высокая контрастность'};
for(const [file,kind,title,themes] of [['01-monograms.html','monograms','Монограммы',['original','dark','light','contrast']],['vscode-monograms/02-inset.html','inset','Тонкие рамки',['dark','light','contrast']]]){const p=file.includes('/')?'../':'';fs.writeFileSync(path.join(root,file),`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} — Kilo Hub</title>${['demo-themes.css','panel.css','refinements.css','scale.css'].map(f=>`<link rel="stylesheet" href="${p+f}">`).join('')}<script defer src="${p}activity.cjs"></script><script defer src="${p}interaction.cjs"></script><script defer src="${p}demo.js"></script></head><body><div class="review"><a href="${p}index.html">← Два дизайна</a><h1>${title}</h1><p>Локальный макет. Раскрытие работает; команды папок и обновление только демонстрируются. Палитры не синхронизируются с VS Code.</p><nav aria-label="Темы">${themes.map(t=>`<a href="#${t}">${labels[t]}</a>`).join('')}</nav></div><main class="theme-grid">${themes.map(t=>`<article class="theme-example" id="${t}"><h2>${labels[t]}</h2>${panel(kind,t)}</article>`).join('')}</main></body></html>`);}
fs.writeFileSync(path.join(root,'index.html'),`<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Два дизайна Kilo Hub</title><link rel="stylesheet" href="panel.css"><main class="review"><h1>Два дизайна Kilo Hub</h1><p>Альтернативные эталоны. Для VSIX ещё предстоит выбрать одну композицию. Темы — демонстрационные.</p>${[['Тонкие рамки','vscode-monograms/02-inset.html',['dark','light','contrast']],['Монограммы · оригинальная композиция','01-monograms.html',['original','dark','light','contrast']]].map(([name,file,themes])=>`<section><h2><a href="${file}">${name}</a></h2><nav>${themes.map(t=>`<a href="${file}#${t}">${labels[t]}</a>`).join('')}</nav></section>`).join('<br>')}<p><a href="../ТЗ реализации дизайна VSIX.md">ТЗ реализации VSIX</a> · <a href="../UX правки.md">UX решения</a></p></main></html>`);
