import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.dirname(fileURLToPath(import.meta.url));
const concepts = [
 ['01-quiet-list','Спокойный список','Монограммы 32 px и разделители; плотность близка к боковой панели.','quiet'],
 ['02-inset','Тонкие рамки','Небольшие блоки с тонкой границей и умеренными интервалами.','inset'],
 ['03-heading','Название впереди','Название слева, буквенный ориентир справа; больше веса у текста.','heading'],
 ['04-guide','Общее поле','Монограммы образуют левую колонку, детали продолжают линию названия.','guide'],
 ['05-labels','Строка-ярлык','Небольшая монограмма над крупным названием; спокойное вертикальное деление.','labels']
];
const themes=[['dark','Тёмная'],['light','Светлая'],['contrast','Высокая контрастность']];
const folders=[['Сайт мастерской','СМ','current'],['Семейный бюджет','СБ','expanded'],['Путешествие по северу','ПС',''],['Каталог работ и вдохновения для новой коллекции','КР',''],['Старый эксперимент','СЭ','missing']];
function folder([name,initials,state]) {
 const missing=state==='missing';
 const titles=missing?['Первые наброски']:['План расходов на осень','Как наглядно сравнить расходы за несколько месяцев','Без названия'];
 return `<details class="folder ${state}" ${state==='expanded'?'open':''}><summary><span class="mono" aria-hidden="true">${initials}</span><span class="identity">${state==='current'?'<span class="current-label">Текущая папка</span>':''}<span class="name">${name}</span>${missing?'<span class="missing-label">Папка не найдена</span>':''}</span><span class="chevron" aria-hidden="true">⌄</span></summary><div class="detail"><p class="path">D:\\Проекты\\${name}</p>${missing?'<p class="warning">Папка не найдена. Открытие недоступно.</p>':''}<div class="actions"><button ${missing?'disabled':''} title="Макет: сменит папку в текущем окне">Открыть в этом окне <span aria-hidden="true">↗</span></button><button ${missing?'disabled':''}>Открыть в новом окне <span aria-hidden="true">⊞</span></button><button ${missing?'disabled':''}>Показать в проводнике <span aria-hidden="true">↗</span></button></div><div class="history"><h3>Последние диалоги</h3><p class="hint">Названия для ориентира. Продолжайте работу в Kilo.</p><ul>${titles.map((t,i)=>`<li><span>${t}</span>${i<2?`<time>${i===0?'Сегодня':'Вчера'}</time>`:''}</li>`).join('')}</ul></div></div></details>`;
}
function panel(mode,theme,missingOpen=false){return `<section class="panel ${mode} demo-${theme}" aria-label="Kilo Hub"><header><strong>Kilo Hub</strong><button class="refresh" title="Макет ручного обновления">↻ <span>Обновить</span></button></header><div class="intro"><h2>Ваши папки</h2></div><div class="folders">${folders.map(f=>folder(f)).join('')}</div></section>`;}
function page(title,body){return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} — Kilo Hub</title><link rel="stylesheet" href="demo-themes.css"><link rel="stylesheet" href="panel.css"></head><body>${body}</body></html>`;}
for(const [slug,title,desc,mode] of concepts){fs.writeFileSync(path.join(root,slug+'.html'),page(title,`<div class="review"><a href="index.html">← Пять вариантов</a><h1>${title}</h1><p>${desc}</p><nav aria-label="Демонстрационные темы">${themes.map(([id,label])=>`<a href="#${id}">${label}</a>`).join('')}</nav><p class="notice">Три статические демонстрации. Автономный HTML не получает тему из VS Code. Кнопки не выполняют команды.</p></div><main class="theme-grid">${themes.map(([id,label])=>`<article class="theme-example" id="${id}"><h2>${label}</h2>${panel(mode,id)}</article>`).join('')}</main>`));}
fs.writeFileSync(path.join(root,'index.html'),page('Пять лаконичных монограмм',`<div class="review"><a href="../monograms/index.html">← Предыдущие монограммы</a><h1>Монограммы в ритме VS Code</h1><p>Пять лаконичных композиций. В каждом варианте — тёмная, светлая и высококонтрастная демонстрации.</p><p class="notice">Панель Kilo Hub без остальных областей редактора. Откройте вариант для сравнения трёх тем. Локальные статические файлы.</p></div><main class="concept-grid">${concepts.map(([slug,title,desc,mode],i)=>`<article class="concept"><div class="caption"><span>0${i+1}</span><h2><a href="${slug}.html">${title} ↗</a></h2><p>${desc}</p><nav>${themes.map(([id,label])=>`<a href="${slug}.html#${id}">${label}</a>`).join('')}</nav></div>${panel(mode,'dark')}</article>`).join('')}</main>`));
